name: CI

on: [pull_request]

jobs:
  lint:
    name: Check linting

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1, 21.0.0, 22.0.0]  # Versões compatíveis com sharp@0.33.5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Check Node.js version
        run: |
          node -v  # Verificar versão do Node.js
          npm -v   # Verificar versão do npm
          yarn -v  # Verificar versão do Yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
